const maxLevel = 30
let levels = [30]

for (let i=1; i<maxLevel; i++){
    levels.push(Math.floor(levels[i-1]*(1+2/3)))
} 

let gameOverPhrases  = [
    "'I should've taken anti-dungeon monster defenses in Wizard School'",
    "'Now my laundry will go forever unfolded'",
    "'#Lula2022'",
    "'Finally!'",
    "'Didn't that orc look like Steve?'",
    "'Sdds da morena'",
    "'Pau que nasce torto nunca se endireita?'",
    "'Ok, that was DEFINETELY the wrong door'",
    "'Picólezin de milho, bom demais'",
    "'Could this be a simulated reality?'",
    "'Now my ghost costume will be REALLY good'",
    "'Eu deveria ter dançado mais Bonde do Tigrão'",
    "'Tu eres puro puro chantaje, puro puro chantaje'",
    "'Akemi Homura, plese stop me from becoming a mahou shoujo'",
    "'Does this hat make me look fat?'",
    "'So Kira was Yagami Raito all along?!'",
    "'We are fighting dreamers'",
    "'I hope he restarts the game soon'",
    "'O Pato sem a pata, quando anda manca'",
    "'Thank you for supporting me. And if you don't...'",
    "'CORONAVIRUS! Shit is real! Shit is getting real!'",
    "'A Lua me traiu'",
    "'A bonekinha não sabe brincar'",
    "'Fly you fools!'",
    "'Fintchy reãis!'",
    "'É o quê que tá aconteceno?!'",
    "'Mirella, corre aqui!'",
    "'Lohane Vêkanandre Sthephany Smith Bueno de HA HA HA...'",
    "'Finally, I'll pay for my sins in Ishval'",
    "'Já acabou, Lorena?'",
    "'Don't follow the light, it's a train'",
    "'All that fit food for nothing'",
    "'I can't believe I'm going to die IN THESE clothes'",
    "'At least it wasn't in the shower'",
    "'I should've worn my good underwear'",
    "'Sashay Away'",
    "'Questão de Ordem, Sr. Presidente'",
    "'Please tell me you've saved some phoenix down'",
    "'Microwave beeps ARE NOT passive-aggressive'",
    "'I don't exist and neither do you'",
    "'I hope I don't have to start from scratch' (you do)"
]

let monsters = [
    {name : "Spider",
    imageSrc : "../images/spider.png",   
    maxSpeed: 3,
    width: 20,
    height: 20,
    health:10,
    maxHealth: 10,
    damage:5,
    expGiven: 10,
    startMinute: 1,
    spawn: 50,
    cooldown: 0
    },

    {name : "Goblin",
    imageSrc : "../images/goblin.png",   
    maxSpeed: 2,
    width: 30,
    height: 30,
    health:20,
    maxHealth: 20,
    damage:10,
    expGiven: 10,
    startMinute: 0,
    spawn: 100,
    cooldown: 0
    },

    {name : "Orc",
    imageSrc : "../images/orc.png",   
    maxSpeed: 2,
    width: 40,
    height: 40,
    health:100,
    maxHealth: 100,
    damage:15,
    expGiven: 30,
    startMinute: 3,
    spawn: 150,
    cooldown: 0
    },

    {name : "Zombie",
    imageSrc : "../images/zombie.png",   
    maxSpeed: 1,
    width: 40,
    height: 40,
    health:80,
    maxHealth: 80,
    damage:30,
    expGiven: 50,
    startMinute: 5,
    spawn: 150,
    cooldown: 0
    },    
    
    {name : "Knight",
    imageSrc : "../images/knight.png",   
    maxSpeed: 3,
    width: 40,
    height: 40,
    health:300,
    maxHealth: 300,
    damage:30,
    expGiven: 70,
    startMinute: 7,
    spawn: 200,
    cooldown: 0
    },    
    
    {name : "Vampire",
    imageSrc : "../images/knight.png",   
    maxSpeed: 3,
    width: 40,
    height: 40,
    health:300,
    maxHealth: 300,
    damage:30,
    expGiven: 70,
    startMinute: 10,
    spawn: 200,
    cooldown: 0
    },    
    
    {name : "Reaper",
    imageSrc : "../images/reaper.png",   
    maxSpeed: 3,
    width: 50,
    height: 50,
    health:300,
    maxHealth: 300,
    damage:30,
    expGiven: 70,
    startMinute: 15,
    spawn: 200,
    cooldown: 0
    },    
    
    {name : "Demon",
    imageSrc : "../images/demon.png",   
    maxSpeed: 3,
    width: 50,
    height: 50,
    health:300,
    maxHealth: 300,
    damage:30,
    expGiven: 70,
    startMinute: 20,
    spawn: 200,
    cooldown: 0
    },    
    
    {name : "Dragon",
    imageSrc : "../images/dragon.png",   
    maxSpeed: 1,
    width: 100,
    height: 100,
    health:300,
    maxHealth: 5000,
    damage:300,
    expGiven: 1000,
    startMinute: 0,
    spawn: 5000,
    cooldown: 0
    }
]

